[package]
name = "git-workspace"
version = "0.1.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"

[dependencies]
toml = "^0.5.1"
serde = "^1.0.97"
git2 = "^0.9.1"
serde_derive = "^1.0.97"
