[package]
name = "git-workspace"
version = "0.1.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
description = "Manage and update personal and work git repos from multiple providers"
license = "MIT"

[dependencies]
toml = "0.5.3"
serde = { version = "1.0.99", features = ["derive"] }
git2 = { version = "0.9.2", default-features = false }
failure = "0.1.5"
structopt = "0.2.18"

[profile.release]
lto = true
