on: [push]

name: CI

jobs:

  build_and_test:
    name: Rust project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --workspace=${GITHUB_WORKSPACE}/workspace add gitlab user tom6
        env:
          -
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --workspace=${GITHUB_WORKSPACE}/workspace update
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}