[[repo]]
path = "github/TheZ3ro/apk2java-linux"
url = "git@github.com:TheZ3ro/apk2java-linux.git"
branch = "master"

[[repo]]
path = "github/django/django-docker-box"
url = "git@github.com:django/django-docker-box.git"
upstream = "git@github.com:orf/django-docker-box.git"
branch = "master"

[[repo]]
path = "github/onfido/faiss_prebuilt"
url = "git@github.com:onfido/faiss_prebuilt.git"
branch = "master"

[[repo]]
path = "github/orf/CTF"
url = "git@github.com:orf/CTF.git"
branch = "master"

[[repo]]
path = "github/orf/Facebook-link-stats"
url = "git@github.com:orf/Facebook-link-stats.git"
branch = "master"

[[repo]]
path = "github/orf/FindMeChicken-GAE"
url = "git@github.com:orf/FindMeChicken-GAE.git"
branch = "master"

[[repo]]
path = "github/orf/FindMeChicken-Twisted"
url = "git@github.com:orf/FindMeChicken-Twisted.git"
branch = "master"

[[repo]]
path = "github/orf/FindMeChicken-mono"
url = "git@github.com:orf/FindMeChicken-mono.git"
branch = "master"

[[repo]]
path = "github/orf/Flask-Hooker"
url = "git@github.com:orf/Flask-Hooker.git"
upstream = "git@github.com:doblel/Flask-Hooker.git"
branch = "master"

[[repo]]
path = "github/orf/Gmail-dumper"
url = "git@github.com:orf/Gmail-dumper.git"
branch = "master"

[[repo]]
path = "github/orf/HtmlToWord"
url = "git@github.com:orf/HtmlToWord.git"
branch = "master"

[[repo]]
path = "github/orf/MovieFinder"
url = "git@github.com:orf/MovieFinder.git"
branch = "master"

[[repo]]
path = "github/orf/NoPriv"
url = "git@github.com:orf/NoPriv.git"
upstream = "git@github.com:RaymiiOrg/NoPriv.git"
branch = "master"

[[repo]]
path = "github/orf/Stream-Framework"
url = "git@github.com:orf/Stream-Framework.git"
upstream = "git@github.com:tschellenbach/Stream-Framework.git"
branch = "master"

[[repo]]
path = "github/orf/TinyLink"
url = "git@github.com:orf/TinyLink.git"
branch = "master"

[[repo]]
path = "github/orf/WikiQuiz"
url = "git@github.com:orf/WikiQuiz.git"
upstream = "git@github.com:alexgreene/WikiQuiz.git"
branch = "master"

[[repo]]
path = "github/orf/Wikipedia-XML-Processor"
url = "git@github.com:orf/Wikipedia-XML-Processor.git"
branch = "master"

[[repo]]
path = "github/orf/aio-pipes"
url = "git@github.com:orf/aio-pipes.git"
branch = "master"

[[repo]]
path = "github/orf/aiohttp"
url = "git@github.com:orf/aiohttp.git"
upstream = "git@github.com:aio-libs/aiohttp.git"
branch = "master"

[[repo]]
path = "github/orf/aiopg"
url = "git@github.com:orf/aiopg.git"
upstream = "git@github.com:aio-libs/aiopg.git"
branch = "master"

[[repo]]
path = "github/orf/aioresponses"
url = "git@github.com:orf/aioresponses.git"
upstream = "git@github.com:pnuckowski/aioresponses.git"
branch = "master"

[[repo]]
path = "github/orf/alfred-pycharm"
url = "git@github.com:orf/alfred-pycharm.git"
branch = "master"

[[repo]]
path = "github/orf/alfred-quip-workflow"
url = "git@github.com:orf/alfred-quip-workflow.git"
branch = "master"

[[repo]]
path = "github/orf/apple-features"
url = "git@github.com:orf/apple-features.git"
branch = "master"

[[repo]]
path = "github/orf/bare-hugo-theme"
url = "git@github.com:orf/bare-hugo-theme.git"
branch = "master"

[[repo]]
path = "github/orf/blackfriday"
url = "git@github.com:orf/blackfriday.git"
upstream = "git@github.com:russross/blackfriday.git"
branch = "master"

[[repo]]
path = "github/orf/blog"
url = "git@github.com:orf/blog.git"
branch = "master"

[[repo]]
path = "github/orf/blog-gatsby"
url = "git@github.com:orf/blog-gatsby.git"
branch = "master"

[[repo]]
path = "github/orf/blog-hugo"
url = "git@github.com:orf/blog-hugo.git"
branch = "master"

[[repo]]
path = "github/orf/broccoli-templater"
url = "git@github.com:orf/broccoli-templater.git"
upstream = "git@github.com:stefanpenner/broccoli-templater.git"
branch = "master"

[[repo]]
path = "github/orf/celery"
url = "git@github.com:orf/celery.git"
upstream = "git@github.com:celery/celery.git"
branch = "master"

[[repo]]
path = "github/orf/clap"
url = "git@github.com:orf/clap.git"
upstream = "git@github.com:clap-rs/clap.git"
branch = "master"

[[repo]]
path = "github/orf/colorama"
url = "git@github.com:orf/colorama.git"
upstream = "git@github.com:tartley/colorama.git"
branch = "master"

[[repo]]
path = "github/orf/comtypes"
url = "git@github.com:orf/comtypes.git"
upstream = "git@github.com:enthought/comtypes.git"
branch = "master"

[[repo]]
path = "github/orf/cookiecutter"
url = "git@github.com:orf/cookiecutter.git"
upstream = "git@github.com:cookiecutter/cookiecutter.git"
branch = "master"

[[repo]]
path = "github/orf/cpe"
url = "git@github.com:orf/cpe.git"
upstream = "git@github.com:nilp0inter/cpe.git"
branch = "develop"

[[repo]]
path = "github/orf/cvsslib"
url = "git@github.com:orf/cvsslib.git"
upstream = "git@github.com:ctxis/cvsslib.git"
branch = "master"

[[repo]]
path = "github/orf/cyborg"
url = "git@github.com:orf/cyborg.git"
branch = "master"

[[repo]]
path = "github/orf/datatables"
url = "git@github.com:orf/datatables.git"
branch = "master"

[[repo]]
path = "github/orf/dd-trace-py"
url = "git@github.com:orf/dd-trace-py.git"
upstream = "git@github.com:DataDog/dd-trace-py.git"
branch = "master"

[[repo]]
path = "github/orf/digest"
url = "git@github.com:orf/digest.git"
branch = "master"

[[repo]]
path = "github/orf/django"
url = "git@github.com:orf/django.git"
upstream = "git@github.com:django/django.git"
branch = "master"

[[repo]]
path = "github/orf/django-choice-object"
url = "git@github.com:orf/django-choice-object.git"
branch = "master"

[[repo]]
path = "github/orf/django-debug-toolbar-template-timings"
url = "git@github.com:orf/django-debug-toolbar-template-timings.git"
branch = "master"

[[repo]]
path = "github/orf/django-docker-box"
url = "git@github.com:orf/django-docker-box.git"
branch = "master"

[[repo]]
path = "github/orf/django-performance-metrics"
url = "git@github.com:orf/django-performance-metrics.git"
branch = "master"

[[repo]]
path = "github/orf/dotfiles"
url = "git@github.com:orf/dotfiles.git"
branch = "master"

[[repo]]
path = "github/orf/endpoint"
url = "git@github.com:orf/endpoint.git"
branch = "master"

[[repo]]
path = "github/orf/exams"
url = "git@github.com:orf/exams.git"
branch = "master"

[[repo]]
path = "github/orf/faiss"
url = "git@github.com:orf/faiss.git"
upstream = "git@github.com:facebookresearch/faiss.git"
branch = "master"

[[repo]]
path = "github/orf/faust"
url = "git@github.com:orf/faust.git"
upstream = "git@github.com:robinhood/faust.git"
branch = "master"

[[repo]]
path = "github/orf/feedtester"
url = "git@github.com:orf/feedtester.git"
branch = "master"

[[repo]]
path = "github/orf/gatekeeper"
url = "git@github.com:orf/gatekeeper.git"
branch = "master"

[[repo]]
path = "github/orf/getshitdone"
url = "git@github.com:orf/getshitdone.git"
branch = "master"

[[repo]]
path = "github/orf/git-workspace"
url = "git@github.com:orf/git-workspace.git"
branch = "master"

[[repo]]
path = "github/orf/git2-rs"
url = "git@github.com:orf/git2-rs.git"
upstream = "git@github.com:rust-lang/git2-rs.git"
branch = "master"

[[repo]]
path = "github/orf/gixy"
url = "git@github.com:orf/gixy.git"
upstream = "git@github.com:yandex/gixy.git"
branch = "master"

[[repo]]
path = "github/orf/gmusicapi"
url = "git@github.com:orf/gmusicapi.git"
upstream = "git@github.com:simon-weber/gmusicapi.git"
branch = "develop"

[[repo]]
path = "github/orf/goal"
url = "git@github.com:orf/goal.git"
upstream = "git@github.com:eatnumber1/goal.git"
branch = "master"

[[repo]]
path = "github/orf/google-cloud-sdk-helm"
url = "git@github.com:orf/google-cloud-sdk-helm.git"
branch = "master"

[[repo]]
path = "github/orf/gping"
url = "git@github.com:orf/gping.git"
branch = "master"

[[repo]]
path = "github/orf/hnewssimulator"
url = "git@github.com:orf/hnewssimulator.git"
branch = "master"

[[repo]]
path = "github/orf/horrible-afl-things"
url = "git@github.com:orf/horrible-afl-things.git"
branch = "master"

[[repo]]
path = "github/orf/howslow_django"
url = "git@github.com:orf/howslow_django.git"
branch = "master"

[[repo]]
path = "github/orf/howslow_flask"
url = "git@github.com:orf/howslow_flask.git"
branch = "master"

[[repo]]
path = "github/orf/hyperium.github.io"
url = "git@github.com:orf/hyperium.github.io.git"
upstream = "git@github.com:hyperium/hyperium.github.io.git"
branch = "master"

[[repo]]
path = "github/orf/icaro"
url = "git@github.com:orf/icaro.git"
upstream = "git@github.com:GianlucaGuarini/icaro.git"
branch = "master"

[[repo]]
path = "github/orf/image-match"
url = "git@github.com:orf/image-match.git"
upstream = "git@github.com:EdjoLabs/image-match.git"
branch = "master"

[[repo]]
path = "github/orf/imageio"
url = "git@github.com:orf/imageio.git"
upstream = "git@github.com:imageio/imageio.git"
branch = "master"

[[repo]]
path = "github/orf/inliner"
url = "git@github.com:orf/inliner.git"
branch = "master"

[[repo]]
path = "github/orf/learnxinyminutes-docs"
url = "git@github.com:orf/learnxinyminutes-docs.git"
upstream = "git@github.com:adambard/learnxinyminutes-docs.git"
branch = "master"

[[repo]]
path = "github/orf/localshop"
url = "git@github.com:orf/localshop.git"
upstream = "git@github.com:mvantellingen/localshop.git"
branch = "develop"

[[repo]]
path = "github/orf/logbook"
url = "git@github.com:orf/logbook.git"
branch = "master"

[[repo]]
path = "github/orf/logbot"
url = "git@github.com:orf/logbot.git"
branch = "master"

[[repo]]
path = "github/orf/logstore"
url = "git@github.com:orf/logstore.git"
branch = "master"

[[repo]]
path = "github/orf/lxml"
url = "git@github.com:orf/lxml.git"
upstream = "git@github.com:lxml/lxml.git"
branch = "master"

[[repo]]
path = "github/orf/mackup"
url = "git@github.com:orf/mackup.git"
upstream = "git@github.com:lra/mackup.git"
branch = "master"

[[repo]]
path = "github/orf/markovify"
url = "git@github.com:orf/markovify.git"
upstream = "git@github.com:jsvine/markovify.git"
branch = "master"

[[repo]]
path = "github/orf/meetuptracker-frontend"
url = "git@github.com:orf/meetuptracker-frontend.git"
branch = "master"

[[repo]]
path = "github/orf/micro-sentry"
url = "git@github.com:orf/micro-sentry.git"
upstream = "git@github.com:tanmulabs/micro-sentry.git"
branch = "master"

[[repo]]
path = "github/orf/model_mommy"
url = "git@github.com:orf/model_mommy.git"
upstream = "git@github.com:berinhard/model_mommy.git"
branch = "master"

[[repo]]
path = "github/orf/node_exporter"
url = "git@github.com:orf/node_exporter.git"
upstream = "git@github.com:prometheus/node_exporter.git"
branch = "master"

[[repo]]
path = "github/orf/nushell"
url = "git@github.com:orf/nushell.git"
upstream = "git@github.com:nushell/nushell.git"
branch = "master"

[[repo]]
path = "github/orf/orf.github.io"
url = "git@github.com:orf/orf.github.io.git"
upstream = "git@github.com:mmistakes/minimal-mistakes.git"
branch = "master"

[[repo]]
path = "github/orf/petal"
url = "git@github.com:orf/petal.git"
branch = "master"

[[repo]]
path = "github/orf/pghero_solo"
url = "git@github.com:orf/pghero_solo.git"
upstream = "git@github.com:bmorton/pghero_solo.git"
branch = "master"

[[repo]]
path = "github/orf/pid"
url = "git@github.com:orf/pid.git"
upstream = "git@github.com:trbs/pid.git"
branch = "master"

[[repo]]
path = "github/orf/pip-tools"
url = "git@github.com:orf/pip-tools.git"
upstream = "git@github.com:jazzband/pip-tools.git"
branch = "master"

[[repo]]
path = "github/orf/pipenv"
url = "git@github.com:orf/pipenv.git"
upstream = "git@github.com:pypa/pipenv.git"
branch = "master"

[[repo]]
path = "github/orf/presentations"
url = "git@github.com:orf/presentations.git"
branch = "master"

[[repo]]
path = "github/orf/pypaper"
url = "git@github.com:orf/pypaper.git"
branch = "master"

[[repo]]
path = "github/orf/pyresize"
url = "git@github.com:orf/pyresize.git"
upstream = "git@github.com:xorpad-og/pyresize.git"
branch = "master"

[[repo]]
path = "github/orf/pysaml2"
url = "git@github.com:orf/pysaml2.git"
upstream = "git@github.com:IdentityPython/pysaml2.git"
branch = "master"

[[repo]]
path = "github/orf/pythonlx_2019_jan"
url = "git@github.com:orf/pythonlx_2019_jan.git"
branch = "master"

[[repo]]
path = "github/orf/resizer"
url = "git@github.com:orf/resizer.git"
branch = "master"

[[repo]]
path = "github/orf/rust-book-demo-server"
url = "git@github.com:orf/rust-book-demo-server.git"
branch = "master"

[[repo]]
path = "github/orf/selectize.js"
url = "git@github.com:orf/selectize.js.git"
upstream = "git@github.com:selectize/selectize.js.git"
branch = "master"

[[repo]]
path = "github/orf/serving"
url = "git@github.com:orf/serving.git"
upstream = "git@github.com:tensorflow/serving.git"
branch = "master"

[[repo]]
path = "github/orf/sid-ctf"
url = "git@github.com:orf/sid-ctf.git"
branch = "master"

[[repo]]
path = "github/orf/simple"
url = "git@github.com:orf/simple.git"
branch = "master"

[[repo]]
path = "github/orf/spam"
url = "git@github.com:orf/spam.git"
branch = "master"

[[repo]]
path = "github/orf/stellar"
url = "git@github.com:orf/stellar.git"
upstream = "git@github.com:fastmonkeys/stellar.git"
branch = "master"

[[repo]]
path = "github/orf/svn-extractor"
url = "git@github.com:orf/svn-extractor.git"
upstream = "git@github.com:anantshri/svn-extractor.git"
branch = "master"

[[repo]]
path = "github/orf/swaggerize-express"
url = "git@github.com:orf/swaggerize-express.git"
upstream = "git@github.com:marvelapp/swaggerize-express.git"
branch = "master"

[[repo]]
path = "github/orf/transmission"
url = "git@github.com:orf/transmission.git"
upstream = "git@github.com:transmission/transmission.git"
branch = "master"

[[repo]]
path = "github/orf/uni_timetables"
url = "git@github.com:orf/uni_timetables.git"
branch = "master"

[[repo]]
path = "github/orf/vulnerable_website"
url = "git@github.com:orf/vulnerable_website.git"
branch = "master"

[[repo]]
path = "github/orf/websocket_stdout_example"
url = "git@github.com:orf/websocket_stdout_example.git"
branch = "master"

[[repo]]
path = "github/orf/wikilink_py"
url = "git@github.com:orf/wikilink_py.git"
branch = "master"

[[repo]]
path = "github/orf/wordinserter"
url = "git@github.com:orf/wordinserter.git"
branch = "master"

[[repo]]
path = "github/orf/workaround"
url = "git@github.com:orf/workaround.git"
branch = "master"

[[repo]]
path = "github/orf/wow_economy"
url = "git@github.com:orf/wow_economy.git"
branch = "master"

[[repo]]
path = "github/orf/xcat"
url = "git@github.com:orf/xcat.git"
branch = "master"

[[repo]]
path = "github/orf/xcat_app"
url = "git@github.com:orf/xcat_app.git"
branch = "master"

[[repo]]
path = "github/orf/xcat_app_old"
url = "git@github.com:orf/xcat_app_old.git"
branch = "master"

[[repo]]
path = "github/orf/xpath-expressions"
url = "git@github.com:orf/xpath-expressions.git"
branch = "master"

[[repo]]
path = "github/orf/zomato-map"
url = "git@github.com:orf/zomato-map.git"
branch = "master"

[[repo]]
path = "gitlab/archived"
url = "git@gitlab.com:tom6/archived.git"
branch = "master"

[[repo]]
path = "gitlab/backend-coding-challenge"
url = "git@gitlab.com:tom6/backend-coding-challenge.git"
branch = "master"

[[repo]]
path = "gitlab/gitlab-ce"
url = "git@gitlab.com:tom6/gitlab-ce.git"
branch = "master"

[[repo]]
path = "gitlab/jiri-gitlab"
url = "git@gitlab.com:tom6/jiri-gitlab.git"
branch = "master"

[[repo]]
path = "gitlab/jiri-mirror"
url = "git@gitlab.com:tom6/jiri-mirror.git"
branch = "master"

[[repo]]
path = "gitlab/metrics-bug"
url = "git@gitlab.com:tom6/metrics-bug.git"
branch = "master"

[[repo]]
path = "gitlab/minimal-ruby-app"
url = "git@gitlab.com:tom6/minimal-ruby-app.git"
branch = "master"

[[repo]]
path = "gitlab/resizer"
url = "git@gitlab.com:tom6/resizer.git"
branch = "master"

[[repo]]
path = "gitlab/test-empty-project"
url = "git@gitlab.com:tom6/test-empty-project.git"

[[repo]]
path = "gitlab/test-lfs"
url = "git@gitlab.com:tom6/test-lfs.git"
branch = "master"
