[[repo]]
path = "github-django/django/asgi_ipc"
url = "git@github.com:django/asgi_ipc.git"
branch = "master"

[[repo]]
path = "github-django/django/asgiref"
url = "git@github.com:django/asgiref.git"
branch = "master"

[[repo]]
path = "github-django/django/channels"
url = "git@github.com:django/channels.git"
branch = "master"

[[repo]]
path = "github-django/django/channels_redis"
url = "git@github.com:django/channels_redis.git"
branch = "master"

[[repo]]
path = "github-django/django/code-of-conduct"
url = "git@github.com:django/code-of-conduct.git"
branch = "master"

[[repo]]
path = "github-django/django/code.djangoproject.com"
url = "git@github.com:django/code.djangoproject.com.git"
branch = "master"

[[repo]]
path = "github-django/django/daphne"
url = "git@github.com:django/daphne.git"
branch = "master"

[[repo]]
path = "github-django/django/deps"
url = "git@github.com:django/deps.git"
branch = "master"

[[repo]]
path = "github-django/django/django"
url = "git@github.com:django/django.git"
branch = "master"

[[repo]]
path = "github-django/django/django-box"
url = "git@github.com:django/django-box.git"
branch = "master"

[[repo]]
path = "github-django/django/django-contrib-comments"
url = "git@github.com:django/django-contrib-comments.git"
branch = "master"

[[repo]]
path = "github-django/django/django-docker-box"
url = "git@github.com:django/django-docker-box.git"
upstream = "git@github.com:orf/django-docker-box.git"
branch = "master"

[[repo]]
path = "github-django/django/django-docs-translations"
url = "git@github.com:django/django-docs-translations.git"
branch = "master"

[[repo]]
path = "github-django/django/django-formtools"
url = "git@github.com:django/django-formtools.git"
branch = "master"

[[repo]]
path = "github-django/django/django-localflavor"
url = "git@github.com:django/django-localflavor.git"
branch = "master"

[[repo]]
path = "github-django/django/djangobench"
url = "git@github.com:django/djangobench.git"
branch = "master"

[[repo]]
path = "github-django/django/djangopeople"
url = "git@github.com:django/djangopeople.git"
upstream = "git@github.com:simonw/djangopeople.net.git"
branch = "master"

[[repo]]
path = "github-django/django/djangoproject.com"
url = "git@github.com:django/djangoproject.com.git"
branch = "master"

[[repo]]
path = "github-django/django/djangosnippets.org"
url = "git@github.com:django/djangosnippets.org.git"
branch = "master"

[[repo]]
path = "github-django/django/ticketbot"
url = "git@github.com:django/ticketbot.git"
branch = "master"
