[[repo]]
path = "gitlab/tom6/backend-coding-challenge"
url = "git@gitlab.com:tom6/backend-coding-challenge.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/jiri-gitlab"
url = "git@gitlab.com:tom6/jiri-gitlab.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/jiri-mirror"
url = "git@gitlab.com:tom6/jiri-mirror.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/metrics-bug"
url = "git@gitlab.com:tom6/metrics-bug.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/minimal-ruby-app"
url = "git@gitlab.com:tom6/minimal-ruby-app.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/resizer"
url = "git@gitlab.com:tom6/resizer.git"
branch = "master"

[[repo]]
path = "gitlab/tom6/test-empty-project"
url = "git@gitlab.com:tom6/test-empty-project.git"

[[repo]]
path = "gitlab/tom6/test-lfs"
url = "git@gitlab.com:tom6/test-lfs.git"
branch = "master"
